### ISSUE TITLE
Python Packages Incompatibility

### ISSUE THREAD

**Issue by ahtsham58** [RaymondLi0/conversational-recommendations#6]
There are actually two problems
1) As prescribed in guidelines, python 2.7 is recommended. But the problem is Pytorch and torch are only compatible with python 3.X. 
So when I upgrade my python version to 3.5, I am successful to install both Pytorch and torch packages.
2) After installing all the required packages, I try to run the "train_sentiment_analysis.py". This script makes use of the "batch_loader.py" file, But the problem is reload function is not defined. So I try to install the python package "importlib" mentioned online to make use of reload() function. However, this package is not available.

So there is deadlock in both these two solutions in order to train and test the model. 
Please  clarify what need to be done?

**Comment by RaymondLi0** [comment]
The code in this repository uses Python 2.7 and will not work with Python 3.X

How are you installing pytorch? On this page https://pytorch.org/get-started/locally/ you get all the information to install pytorch on your own platform

**Comment by ahtsham58** [comment]
Thanks for response. I was using windows platform initially, but now switched to Linux and successfully configured the model.
